// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt62Vs_okejzISqJC3jwtm7jN9gdpTir8',
    appId: '1:159266541498:android:b939f7de767724f2eed783',
    messagingSenderId: '159266541498',
    projectId: 'innoride-85b4b',
    storageBucket: 'innoride-85b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGIebZCiSk0XI4WrDLY1UZ7MvWRLkrmI',
    appId: '1:159266541498:ios:d9b778a8317f37f7eed783',
    messagingSenderId: '159266541498',
    projectId: 'innoride-85b4b',
    storageBucket: 'innoride-85b4b.firebasestorage.app',
    androidClientId: '159266541498-fva4f2vfjdsss9u182ll0jcjqg1v9cvq.apps.googleusercontent.com',
    iosClientId: '159266541498-8u0dktn0hia163arigcdq9lhqvheqgsv.apps.googleusercontent.com',
    iosBundleId: 'com.innorider',
  );
}
